[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
streamstake_contracts = "5BxFJmMoRoF4PPeHqw8RCwv4QJuPeQYohYbnYcorGr7B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
